import net.fabricmc.loom.task.prod.ClientProductionRunTask

plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id "org.jetbrains.kotlin.jvm" version "${kotlin_version}"
}

version = mod_version
group = maven_group

base {
    archivesName = archives_base_name
}

repositories {
    maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/maucon/maucon-framework")
        credentials {
            username = System.getenv("GITHUB_PACKAGES_NAME")
            password = System.getenv("GITHUB_PACKAGES_TOKEN")
        }
    }
    maven { url = 'https://maven.nucleoid.xyz/' }
    exclusiveContent {
        forRepository {
            maven {
                name = 'GeckoLib'
                url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
            }
        }
        filter { includeGroupAndSubgroups('com.geckolib') }
    }
}

loom {
    log4jConfigs.from(file("src/main/resources/log4j.xml"))
    accessWidenerPath = file("src/main/resources/mcendgame.accesswidener")

    splitEnvironmentSourceSets()

    mods {
        "mcendgame" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

fabricApi {
    configureDataGeneration {
        client = true
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    implementation "net.fabricmc:fabric-language-kotlin:${fabric_kotlin_version}"

    implementation "xyz.nucleoid:fantasy:${fantasy_version}+${minecraft_version}"
    implementation "com.geckolib:geckolib-fabric-${minecraft_version}:${geckolib_version}"

    implementation "de.maucon:maucon-framework:2.0.1"

    include "de.maucon:maucon-framework:2.0.1"
    include "org.jetbrains.kotlin:kotlin-reflect"
    include "org.reflections:reflections:0.10.2"
    include "org.slf4j:slf4j-api:2.0.17"
    include "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.1"
    include "org.javassist:javassist:3.30.2-GA"

    testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"
}

processResources {
    inputs.property "version", version

    filesMatching("fabric.mod.json") {
        expand "version": version
    }
}

kotlin {
    jvmToolchain(25)
}

java {
    withSourcesJar()
}

test {
    useJUnitPlatform()
}

fabricApi {
    configureTests {
        createSourceSet = true
        modId = "mod-test-${project.name}"
        enableGameTests = true // Default is true
        enableClientGameTests = true // Default is true
        eula = true // By setting this to true, you agree to the Minecraft EULA.
    }
}

tasks.register("runProductionClientGameTest", ClientProductionRunTask) {
    jvmArgs.add("-Dfabric.client.gametest")
    // Whether to use XVFB to run the game, using a virtual framebuffer. This is useful for headless CI environments.
    // Defaults to true only on Linux and when the "CI" environment variable is set.
    // XVFB must be installed, on Debian-based systems you can install it with: `apt install xvfb`
    useXVFB = true
}

jar {
    from("LICENSE") {
        rename { "${it}_${base.archivesName.get()}" }
    }
}