org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_version=1.5.1+26.2
maven_group=de.fuballer.mcendgame
archives_base_name=MCEndgame

# check on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.154.2+26.2

kotlin_version=2.4.0
fabric_kotlin_version=1.13.12+kotlin.2.4.0

# other dependencies
fantasy_version=0.8.2
geckolib_version=5.5.3