package de.fuballer.mcendgame.main.component.item.equipment.enchantment

import net.minecraft.enchantment.Enchantment
import net.minecraft.enchantment.Enchantments
import net.minecraft.registry.RegistryKey

enum class EquipmentEnchantment(
    val enchantment: RegistryKey<Enchantment>,
    val level: Int
) {
    // all-purpose
    MENDING(Enchantments.MENDING, 1),
    UNBREAKING_1(Enchantments.UNBREAKING, 1),
    UNBREAKING_2(Enchantments.UNBREAKING, 2),
    UNBREAKING_3(Enchantments.UNBREAKING, 3),
    CURSE_OF_VANISHING(Enchantments.VANISHING_CURSE, 1),

    // all-purpose armor
    BLAST_PROTECTION_1(Enchantments.BLAST_PROTECTION, 1),
    BLAST_PROTECTION_2(Enchantments.BLAST_PROTECTION, 2),
    BLAST_PROTECTION_3(Enchantments.BLAST_PROTECTION, 3),
    BLAST_PROTECTION_4(Enchantments.BLAST_PROTECTION, 4),
    CURSE_OF_BINDING(Enchantments.BINDING_CURSE, 1),
    FIRE_PROTECTION_1(Enchantments.FIRE_PROTECTION, 1),
    FIRE_PROTECTION_2(Enchantments.FIRE_PROTECTION, 2),
    FIRE_PROTECTION_3(Enchantments.FIRE_PROTECTION, 3),
    FIRE_PROTECTION_4(Enchantments.FIRE_PROTECTION, 4),
    PROJECTILE_PROTECTION_1(Enchantments.PROJECTILE_PROTECTION, 1),
    PROJECTILE_PROTECTION_2(Enchantments.PROJECTILE_PROTECTION, 2),
    PROJECTILE_PROTECTION_3(Enchantments.PROJECTILE_PROTECTION, 3),
    PROJECTILE_PROTECTION_4(Enchantments.PROJECTILE_PROTECTION, 4),
    PROTECTION_1(Enchantments.PROTECTION, 1),
    PROTECTION_2(Enchantments.PROTECTION, 2),
    PROTECTION_3(Enchantments.PROTECTION, 3),
    PROTECTION_4(Enchantments.PROTECTION, 4),
    THORNS_1(Enchantments.THORNS, 1),
    THORNS_2(Enchantments.THORNS, 2),
    THORNS_3(Enchantments.THORNS, 3),

    // armor
    AQUA_AFFINITY_1(Enchantments.AQUA_AFFINITY, 1),
    DEPTH_STRIDER_1(Enchantments.DEPTH_STRIDER, 1),
    DEPTH_STRIDER_2(Enchantments.DEPTH_STRIDER, 2),
    DEPTH_STRIDER_3(Enchantments.DEPTH_STRIDER, 3),
    FEATHER_FALLING_1(Enchantments.FEATHER_FALLING, 1),
    FEATHER_FALLING_2(Enchantments.FEATHER_FALLING, 2),
    FEATHER_FALLING_3(Enchantments.FEATHER_FALLING, 3),
    FEATHER_FALLING_4(Enchantments.FEATHER_FALLING, 4),
    FROST_WALKER_1(Enchantments.FROST_WALKER, 1),
    FROST_WALKER_2(Enchantments.FROST_WALKER, 2),
    RESPIRATION_1(Enchantments.RESPIRATION, 1),
    RESPIRATION_2(Enchantments.RESPIRATION, 2),
    RESPIRATION_3(Enchantments.RESPIRATION, 3),
    SOUL_SPEED_1(Enchantments.SOUL_SPEED, 1),
    SOUL_SPEED_2(Enchantments.SOUL_SPEED, 2),
    SOUL_SPEED_3(Enchantments.SOUL_SPEED, 3),
    SWIFT_SNEAK_1(Enchantments.SWIFT_SNEAK, 1),
    SWIFT_SNEAK_2(Enchantments.SWIFT_SNEAK, 2),
    SWIFT_SNEAK_3(Enchantments.SWIFT_SNEAK, 3),

    // trident
    CHANNELING(Enchantments.CHANNELING, 1),
    IMPALING_1(Enchantments.IMPALING, 1),
    IMPALING_2(Enchantments.IMPALING, 2),
    IMPALING_3(Enchantments.IMPALING, 3),
    IMPALING_4(Enchantments.IMPALING, 4),
    IMPALING_5(Enchantments.IMPALING, 5),
    LOYALTY_1(Enchantments.LOYALTY, 1),
    LOYALTY_2(Enchantments.LOYALTY, 2),
    LOYALTY_3(Enchantments.LOYALTY, 3),
    RIPTIDE_1(Enchantments.RIPTIDE, 1),
    RIPTIDE_2(Enchantments.RIPTIDE, 2),
    RIPTIDE_3(Enchantments.RIPTIDE, 3),

    // mace
    DENSITY_1(Enchantments.DENSITY, 1),
    DENSITY_2(Enchantments.DENSITY, 2),
    DENSITY_3(Enchantments.DENSITY, 3),
    DENSITY_4(Enchantments.DENSITY, 4),
    DENSITY_5(Enchantments.DENSITY, 5),
    BREACH_1(Enchantments.BREACH, 1),
    BREACH_2(Enchantments.BREACH, 2),
    BREACH_3(Enchantments.BREACH, 3),
    BREACH_4(Enchantments.BREACH, 4),
    WINDBURST_1(Enchantments.WIND_BURST, 1),
    WINDBURST_2(Enchantments.WIND_BURST, 2),
    WINDBURST_3(Enchantments.WIND_BURST, 3),

    // melee weapons
    BANE_OF_ARTHROPODS_1(Enchantments.BANE_OF_ARTHROPODS, 1),
    BANE_OF_ARTHROPODS_2(Enchantments.BANE_OF_ARTHROPODS, 2),
    BANE_OF_ARTHROPODS_3(Enchantments.BANE_OF_ARTHROPODS, 3),
    BANE_OF_ARTHROPODS_4(Enchantments.BANE_OF_ARTHROPODS, 4),
    BANE_OF_ARTHROPODS_5(Enchantments.BANE_OF_ARTHROPODS, 5),
    FIRE_ASPECT_1(Enchantments.FIRE_ASPECT, 1),
    FIRE_ASPECT_2(Enchantments.FIRE_ASPECT, 2),
    LOOTING_1(Enchantments.LOOTING, 1),
    LOOTING_2(Enchantments.LOOTING, 2),
    LOOTING_3(Enchantments.LOOTING, 3),
    KNOCKBACK_1(Enchantments.KNOCKBACK, 1),
    KNOCKBACK_2(Enchantments.KNOCKBACK, 2),
    SHARPNESS_1(Enchantments.SHARPNESS, 1),
    SHARPNESS_2(Enchantments.SHARPNESS, 2),
    SHARPNESS_3(Enchantments.SHARPNESS, 3),
    SHARPNESS_4(Enchantments.SHARPNESS, 4),
    SHARPNESS_5(Enchantments.SHARPNESS, 5),
    SMITE_1(Enchantments.SMITE, 1),
    SMITE_2(Enchantments.SMITE, 2),
    SMITE_3(Enchantments.SMITE, 3),
    SMITE_4(Enchantments.SMITE, 4),
    SMITE_5(Enchantments.SMITE, 5),
    SWEEPING_EDGE_1(Enchantments.SWEEPING_EDGE, 1),
    SWEEPING_EDGE_2(Enchantments.SWEEPING_EDGE, 2),
    SWEEPING_EDGE_3(Enchantments.SWEEPING_EDGE, 3),

    // ranged weapons
    FLAME(Enchantments.FLAME, 1),
    INFINITY(Enchantments.INFINITY, 1),
    POWER_1(Enchantments.POWER, 1),
    POWER_2(Enchantments.POWER, 2),
    POWER_3(Enchantments.POWER, 3),
    POWER_4(Enchantments.POWER, 4),
    POWER_5(Enchantments.POWER, 5),
    PUNCH_1(Enchantments.PUNCH, 1),
    PUNCH_2(Enchantments.PUNCH, 2),

    // crossbow
    MULTISHOT(Enchantments.MULTISHOT, 1),
    PIERCING_1(Enchantments.PIERCING, 1),
    PIERCING_2(Enchantments.PIERCING, 2),
    PIERCING_3(Enchantments.PIERCING, 3),
    PIERCING_4(Enchantments.PIERCING, 4),
    QUICK_CHARGE_1(Enchantments.QUICK_CHARGE, 1),
    QUICK_CHARGE_2(Enchantments.QUICK_CHARGE, 2),
    QUICK_CHARGE_3(Enchantments.QUICK_CHARGE, 3),

    // tools
    EFFICIENCY_1(Enchantments.EFFICIENCY, 1),
    EFFICIENCY_2(Enchantments.EFFICIENCY, 2),
    EFFICIENCY_3(Enchantments.EFFICIENCY, 3),
    EFFICIENCY_4(Enchantments.EFFICIENCY, 4),
    EFFICIENCY_5(Enchantments.EFFICIENCY, 5),
    FORTUNE_1(Enchantments.FORTUNE, 1),
    FORTUNE_2(Enchantments.FORTUNE, 2),
    FORTUNE_3(Enchantments.FORTUNE, 3),
    LUCK_OF_THE_SEA_1(Enchantments.LUCK_OF_THE_SEA, 1),
    LUCK_OF_THE_SEA_2(Enchantments.LUCK_OF_THE_SEA, 2),
    LUCK_OF_THE_SEA_3(Enchantments.LUCK_OF_THE_SEA, 3),
    LURE_1(Enchantments.LURE, 1),
    LURE_2(Enchantments.LURE, 2),
    LURE_3(Enchantments.LURE, 3),
    SILK_TOUCH(Enchantments.SILK_TOUCH, 1),
}