package de.fuballer.mcendgame.component.dungeon.tweaks.block_interaction

import org.bukkit.Material

object BlockInteractionSettings {
    val BREAKABLE_BLOCKS = listOf(
        Material.SHORT_GRASS,
        Material.TALL_GRASS,
        Material.FERN,
        Material.LARGE_FERN,
        Material.GLOW_BERRIES,
        Material.BIG_DRIPLEAF,
        Material.BIG_DRIPLEAF_STEM,
        Material.SMALL_DRIPLEAF,
        Material.CAVE_VINES,
        Material.CAVE_VINES_PLANT,
        Material.DEAD_BUSH,
        Material.HANGING_ROOTS,
        Material.DANDELION,
        Material.POPPY,
        Material.BLUE_ORCHID,
        Material.ALLIUM,
        Material.AZURE_BLUET,
        Material.ORANGE_TULIP,
        Material.PINK_TULIP,
        Material.RED_TULIP,
        Material.WHITE_TULIP,
        Material.OXEYE_DAISY,
        Material.CORNFLOWER,
        Material.LILY_OF_THE_VALLEY,
        Material.TORCHFLOWER,
        Material.LILY_PAD,
        Material.LILAC,
        Material.SUNFLOWER,
        Material.BROWN_MUSHROOM,
        Material.RED_MUSHROOM,
        Material.COBWEB,
        Material.PITCHER_PLANT,
        Material.SEAGRASS,
        Material.TALL_SEAGRASS,
        Material.SPORE_BLOSSOM,
        Material.KELP_PLANT,
        Material.SUGAR_CANE,

        Material.BRAIN_CORAL,
        Material.BUBBLE_CORAL,
        Material.FIRE_CORAL,
        Material.HORN_CORAL,
        Material.TUBE_CORAL,
        Material.DEAD_BRAIN_CORAL,
        Material.DEAD_BUBBLE_CORAL,
        Material.DEAD_FIRE_CORAL,
        Material.DEAD_HORN_CORAL,
        Material.DEAD_TUBE_CORAL,

        Material.DEAD_BRAIN_CORAL_FAN,
        Material.DEAD_BUBBLE_CORAL_FAN,
        Material.DEAD_FIRE_CORAL_FAN,
        Material.DEAD_HORN_CORAL_FAN,
        Material.DEAD_TUBE_CORAL_FAN,
        Material.BRAIN_CORAL_FAN,
        Material.BUBBLE_CORAL_FAN,
        Material.FIRE_CORAL_FAN,
        Material.HORN_CORAL_FAN,
        Material.TUBE_CORAL_FAN,

        Material.DEAD_BRAIN_CORAL_WALL_FAN,
        Material.DEAD_BUBBLE_CORAL_WALL_FAN,
        Material.DEAD_FIRE_CORAL_WALL_FAN,
        Material.DEAD_HORN_CORAL_WALL_FAN,
        Material.DEAD_TUBE_CORAL_WALL_FAN,
        Material.BRAIN_CORAL_WALL_FAN,
        Material.BUBBLE_CORAL_WALL_FAN,
        Material.FIRE_CORAL_WALL_FAN,
        Material.HORN_CORAL_WALL_FAN,
        Material.TUBE_CORAL_WALL_FAN,
    )
}