package de.fuballer.mcendgame.component.item.equipment

import org.bukkit.enchantments.Enchantment

enum class ItemEnchantment(
    val enchantment: Enchantment,
    val level: Int
) {
    // all-purpose
    MENDING(Enchantment.MENDING, 1),
    UNBREAKING_1(Enchantment.UNBREAKING, 1),
    UNBREAKING_2(Enchantment.UNBREAKING, 2),
    UNBREAKING_3(Enchantment.UNBREAKING, 3),
    CURSE_OF_VANISHING(Enchantment.VANISHING_CURSE, 1),

    // all-purpose armor
    BLAST_PROTECTION_1(Enchantment.BLAST_PROTECTION, 1),
    BLAST_PROTECTION_2(Enchantment.BLAST_PROTECTION, 2),
    BLAST_PROTECTION_3(Enchantment.BLAST_PROTECTION, 3),
    BLAST_PROTECTION_4(Enchantment.BLAST_PROTECTION, 4),
    CURSE_OF_BINDING(Enchantment.BINDING_CURSE, 1),
    FIRE_PROTECTION_1(Enchantment.FIRE_PROTECTION, 1),
    FIRE_PROTECTION_2(Enchantment.FIRE_PROTECTION, 2),
    FIRE_PROTECTION_3(Enchantment.FIRE_PROTECTION, 3),
    FIRE_PROTECTION_4(Enchantment.FIRE_PROTECTION, 4),
    PROJECTILE_PROTECTION_1(Enchantment.PROJECTILE_PROTECTION, 1),
    PROJECTILE_PROTECTION_2(Enchantment.PROJECTILE_PROTECTION, 2),
    PROJECTILE_PROTECTION_3(Enchantment.PROJECTILE_PROTECTION, 3),
    PROJECTILE_PROTECTION_4(Enchantment.PROJECTILE_PROTECTION, 4),
    PROTECTION_1(Enchantment.PROTECTION, 1),
    PROTECTION_2(Enchantment.PROTECTION, 2),
    PROTECTION_3(Enchantment.PROTECTION, 3),
    PROTECTION_4(Enchantment.PROTECTION, 4),
    THORNS_1(Enchantment.THORNS, 1),
    THORNS_2(Enchantment.THORNS, 2),
    THORNS_3(Enchantment.THORNS, 3),

    // armor
    AQUA_AFFINITY_1(Enchantment.AQUA_AFFINITY, 1),
    DEPTH_STRIDER_1(Enchantment.DEPTH_STRIDER, 1),
    DEPTH_STRIDER_2(Enchantment.DEPTH_STRIDER, 2),
    DEPTH_STRIDER_3(Enchantment.DEPTH_STRIDER, 3),
    FEATHER_FALLING_1(Enchantment.FEATHER_FALLING, 1),
    FEATHER_FALLING_2(Enchantment.FEATHER_FALLING, 2),
    FEATHER_FALLING_3(Enchantment.FEATHER_FALLING, 3),
    FEATHER_FALLING_4(Enchantment.FEATHER_FALLING, 4),
    FROST_WALKER_1(Enchantment.FROST_WALKER, 1),
    FROST_WALKER_2(Enchantment.FROST_WALKER, 2),
    RESPIRATION_1(Enchantment.RESPIRATION, 1),
    RESPIRATION_2(Enchantment.RESPIRATION, 2),
    RESPIRATION_3(Enchantment.RESPIRATION, 3),
    SOUL_SPEED_1(Enchantment.SOUL_SPEED, 1),
    SOUL_SPEED_2(Enchantment.SOUL_SPEED, 2),
    SOUL_SPEED_3(Enchantment.SOUL_SPEED, 3),
    SWIFT_SNEAK_1(Enchantment.SWIFT_SNEAK, 1),
    SWIFT_SNEAK_2(Enchantment.SWIFT_SNEAK, 2),
    SWIFT_SNEAK_3(Enchantment.SWIFT_SNEAK, 3),

    // trident
    CHANNELING(Enchantment.CHANNELING, 1),
    IMPALING_1(Enchantment.IMPALING, 1),
    IMPALING_2(Enchantment.IMPALING, 2),
    IMPALING_3(Enchantment.IMPALING, 3),
    IMPALING_4(Enchantment.IMPALING, 4),
    IMPALING_5(Enchantment.IMPALING, 5),
    LOYALTY_1(Enchantment.LOYALTY, 1),
    LOYALTY_2(Enchantment.LOYALTY, 2),
    LOYALTY_3(Enchantment.LOYALTY, 3),
    RIPTIDE_1(Enchantment.RIPTIDE, 1),
    RIPTIDE_2(Enchantment.RIPTIDE, 2),
    RIPTIDE_3(Enchantment.RIPTIDE, 3),

    // mace
    DENSITY_1(Enchantment.DENSITY, 1),
    DENSITY_2(Enchantment.DENSITY, 2),
    DENSITY_3(Enchantment.DENSITY, 3),
    DENSITY_4(Enchantment.DENSITY, 4),
    DENSITY_5(Enchantment.DENSITY, 5),
    BREACH_1(Enchantment.BREACH, 1),
    BREACH_2(Enchantment.BREACH, 2),
    BREACH_3(Enchantment.BREACH, 3),
    BREACH_4(Enchantment.BREACH, 4),
    WINDBURST_1(Enchantment.WIND_BURST, 1),
    WINDBURST_2(Enchantment.WIND_BURST, 2),
    WINDBURST_3(Enchantment.WIND_BURST, 3),

    // melee weapons
    BANE_OF_ARTHROPODS_1(Enchantment.BANE_OF_ARTHROPODS, 1),
    BANE_OF_ARTHROPODS_2(Enchantment.BANE_OF_ARTHROPODS, 2),
    BANE_OF_ARTHROPODS_3(Enchantment.BANE_OF_ARTHROPODS, 3),
    BANE_OF_ARTHROPODS_4(Enchantment.BANE_OF_ARTHROPODS, 4),
    BANE_OF_ARTHROPODS_5(Enchantment.BANE_OF_ARTHROPODS, 5),
    FIRE_ASPECT_1(Enchantment.FIRE_ASPECT, 1),
    FIRE_ASPECT_2(Enchantment.FIRE_ASPECT, 2),
    LOOTING_1(Enchantment.LOOTING, 1),
    LOOTING_2(Enchantment.LOOTING, 2),
    LOOTING_3(Enchantment.LOOTING, 3),
    KNOCKBACK_1(Enchantment.KNOCKBACK, 1),
    KNOCKBACK_2(Enchantment.KNOCKBACK, 2),
    SHARPNESS_1(Enchantment.SHARPNESS, 1),
    SHARPNESS_2(Enchantment.SHARPNESS, 2),
    SHARPNESS_3(Enchantment.SHARPNESS, 3),
    SHARPNESS_4(Enchantment.SHARPNESS, 4),
    SHARPNESS_5(Enchantment.SHARPNESS, 5),
    SMITE_1(Enchantment.SMITE, 1),
    SMITE_2(Enchantment.SMITE, 2),
    SMITE_3(Enchantment.SMITE, 3),
    SMITE_4(Enchantment.SMITE, 4),
    SMITE_5(Enchantment.SMITE, 5),
    SWEEPING_EDGE_1(Enchantment.SWEEPING_EDGE, 1),
    SWEEPING_EDGE_2(Enchantment.SWEEPING_EDGE, 2),
    SWEEPING_EDGE_3(Enchantment.SWEEPING_EDGE, 3),

    // ranged weapons
    FLAME(Enchantment.FLAME, 1),
    INFINITY(Enchantment.INFINITY, 1),
    POWER_1(Enchantment.POWER, 1),
    POWER_2(Enchantment.POWER, 2),
    POWER_3(Enchantment.POWER, 3),
    POWER_4(Enchantment.POWER, 4),
    POWER_5(Enchantment.POWER, 5),
    PUNCH_1(Enchantment.PUNCH, 1),
    PUNCH_2(Enchantment.PUNCH, 2),

    // crossbow
    MULTISHOT(Enchantment.MULTISHOT, 1),
    PIERCING_1(Enchantment.PIERCING, 1),
    PIERCING_2(Enchantment.PIERCING, 2),
    PIERCING_3(Enchantment.PIERCING, 3),
    PIERCING_4(Enchantment.PIERCING, 4),
    QUICK_CHARGE_1(Enchantment.QUICK_CHARGE, 1),
    QUICK_CHARGE_2(Enchantment.QUICK_CHARGE, 2),
    QUICK_CHARGE_3(Enchantment.QUICK_CHARGE, 3),

    // tools
    EFFICIENCY_1(Enchantment.EFFICIENCY, 1),
    EFFICIENCY_2(Enchantment.EFFICIENCY, 2),
    EFFICIENCY_3(Enchantment.EFFICIENCY, 3),
    EFFICIENCY_4(Enchantment.EFFICIENCY, 4),
    EFFICIENCY_5(Enchantment.EFFICIENCY, 5),
    FORTUNE_1(Enchantment.FORTUNE, 1),
    FORTUNE_2(Enchantment.FORTUNE, 2),
    FORTUNE_3(Enchantment.FORTUNE, 3),
    LUCK_OF_THE_SEA_1(Enchantment.LUCK_OF_THE_SEA, 1),
    LUCK_OF_THE_SEA_2(Enchantment.LUCK_OF_THE_SEA, 2),
    LUCK_OF_THE_SEA_3(Enchantment.LUCK_OF_THE_SEA, 3),
    LURE_1(Enchantment.LURE, 1),
    LURE_2(Enchantment.LURE, 2),
    LURE_3(Enchantment.LURE, 3),
    SILK_TOUCH(Enchantment.SILK_TOUCH, 1),
    ;
}