name: build
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb

      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup gradle cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: |
            ~/.gradle/loom-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Grant gradle permissions
        run: chmod +x ./gradlew

      - name: Gradle build
        env:
          GITHUB_PACKAGES_NAME: ${{ github.actor }}
          GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew runDatagen
          ./gradlew build

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/

      - name: Upload build artifacts
        id: artifact-upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: 'build-jars'
          path: build/libs/

      - name: Notify webhook
        if: github.ref == 'refs/heads/master'
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -H "x-webhook-auth: ${{ secrets.WEBHOOK_AUTH }}" \
            -d "{\"artifact-id\": \"${{ steps.artifact-upload.outputs.artifact-id }}\"}"

  client_game_test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb

      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup gradle cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: |
            ~/.gradle/loom-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Grant gradle permissions
        run: chmod +x ./gradlew

      - name: Run client game tests
        env:
          GITHUB_PACKAGES_NAME: ${{ github.actor }}
          GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew runDatagen
          ./gradlew runProductionClientGameTest

      - name: Upload test screenshots
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: 'test-screenshots'
          path: run/screenshots/